### ISSUE TITLE
Missing download_model.sh Script in text2motion Directory

### ISSUE THREAD

**Issue by Marlod390** [CSJasper/HMTV#2]
Hello,

I'm attempting to set up the environment following the Readme file. It specifies that I should run a script named `download_model.sh` to obtain the pretrained models. However, upon navigating to the `text2motion` directory, I found that this script is missing.

Then I successfully executed the `prepare_body_models.sh` and `prepare_t2v.sh` scripts and found that the download_model.sh script is located in the "text2motion/prepare" directory. I want to confirm the correct directory to run the "download_model.sh" script to ensure the pretrained model is downloaded and placed in the appropriate location.

Can you provide further instructions about the correct use of "download_model.sh" or update the Readme file with the necessary steps if this information is currently missing?

Thanks in advance

**Comment by CSJasper** [comment]
Thanks your interests and thanks for pointing out the error in our repository. We accidentally do not update our repo but now it is updated. The `download_models.sh` is unnecessary script so you don't think about it.
And we have updated the README with solutions for the known issues to date.
Thank you once again.
